### ISSUE TITLE
License

### ISSUE THREAD

**Issue by cortner** [baggepinnen/FluxOptTools.jl#11]
Hi @baggepinnen -- Would you be willing to put a license in your repository and register it? This is a really useful package. We'd love to integrate it into our work, but not sure we are allowed? Thank you!

**Comment by baggepinnen** [comment]
Hello!

Sure, the LICENSE is added, I'll trigger registration if tests pass with added compat bounds

**Comment by baggepinnen** [comment]
@JuliaRegistrator register

**Comment by baggepinnen** [comment]
@JuliaRegistrator register

**Comment by cortner** [comment]
fantastic - thanks a lot!!
