### ISSUE TITLE
ERROR: MethodError: no method matching Float64(::Tracker.TrackedReal{Float32})

### ISSUE THREAD

**Issue by athulsudheesh** [baggepinnen/FluxOptTools.jl#2]
Tried running the example and received this error while running this line 
`lossfun, gradfun, fg!, p0 = optfuns(loss, pars)`

`ERROR: MethodError: no method matching Float64(::Tracker.TrackedReal{Float32})

Closest candidates are:
Float64(::Real, ::RoundingMode) where T<:AbstractFloat at rounding.jl:194
Float64(::T<:Number) where T<:Number at boot.jl:741
Float64(::Int8) at float.jl:60`

**Comment by baggepinnen** [comment]
Yeah, this package does not work together with the Tracker backend of Flux, you must switch to Zygote
